import { UserProfile, VerificationItem, Opportunity, RoadmapLevel, SimulatorFactor } from "./types";

export const initialProfile: UserProfile = {
  name: "Harsh",
  avatar: "https://api.dicebear.com/7.x/identicon/svg?seed=Harsh&backgroundColor=e0f2fe",
  university: "National Institute of Technology",
  major: "Computer Science & Engineering",
  gpa: 3.82,
  graduationYear: 2027,
  currentTrustScore: 680,
  category: "Engineering / Technology",
};

export const initialVerificationItems: VerificationItem[] = [
  {
    id: "v-student-status",
    name: "Enrolled Student Status",
    category: "academic",
    sourceName: "University OAuth Registrar",
    status: "verified",
    lastUpdated: "2026-05-15",
    points: 150,
    details: "Verifies standard full-time student status, year, and institution validity.",
  },
  {
    id: "v-transcript",
    name: "Official CGPA Transcript",
    category: "academic",
    sourceName: "National Digilocker Core API",
    status: "verified",
    lastUpdated: "2026-05-18",
    points: 200,
    details: "CGPA of 9.55 / 10.00 verified with active academic record.",
  },
  {
    id: "v-github",
    name: "Developer Skill Signature",
    category: "skills",
    sourceName: "GitHub OAuth Sandbox API",
    status: "verified",
    lastUpdated: "2026-05-20",
    points: 180,
    details: "14 repositories indexed, including 3 original systems. 52 contributions resolved.",
  },
  {
    id: "v-linkedin",
    name: "Linkedin Professional Profile",
    category: "professional",
    sourceName: "LinkedIn Talent API Integration",
    status: "verified",
    lastUpdated: "2026-05-22",
    points: 100,
    details: "Verified headline match: 'CS Junior @ NIT | Budding Systems Engineer'.",
  },
  {
    id: "v-internship",
    name: "Software Engineering Summer Offer",
    category: "professional",
    sourceName: "Corporate HR System Integration or PDF Audit",
    status: "pending",
    lastUpdated: "Not Verified",
    points: 120,
    details: "Requires upload of Signed Summer 2026 Internship Offer Letter or HR manager endorsement.",
  },
  {
    id: "v-club-leadership",
    name: "Google Developer Group Lead Status",
    category: "leadership",
    sourceName: "GDG Global Director Registry",
    status: "not_connected",
    lastUpdated: "Never",
    points: 100,
    details: "Connect GDG/DSC community records or official student body certificate.",
  },
];

export const initialOpportunities: Opportunity[] = [
  // 💻 Engineering / Technology
  {
    id: "op-aws",
    title: "AWS Activate Founder Credits",
    provider: "Amazon Web Services",
    category: "credit",
    description: "Receive essential cloud server credits, architectural assistance, and expert office hours tailored for ambitious student projects.",
    requiredScore: 650,
    rewardValue: "$5,000 Cloud Credits",
    status: "unlocked",
    linkText: "Activate AWS Grant",
    targetCategory: "Engineering / Technology",
  },
  {
    id: "op-tech-innovators",
    title: "Future of Tech Scholarship",
    provider: "Tech Innovators Foundation",
    category: "scholarship",
    description: "Full-tuition scholarship awarded to high-performing technical students exhibiting deep coding proficiency and verifiable academic honors.",
    requiredScore: 700,
    rewardValue: "$10,000 Annual Grant",
    status: "locked",
    linkText: "Apply via Passport",
    targetCategory: "Engineering / Technology",
  },
  {
    id: "op-yc",
    title: "Y-Combinator Pre-Screening Fast-Track",
    provider: "Y-Combinator Network",
    category: "accelerator",
    description: "Fast-track pre-screening pipeline where high-TrustScore student developers are evaluated directly by partner general partners.",
    requiredScore: 740,
    rewardValue: "Priority GP Meeting",
    status: "locked",
    linkText: "Submit Pre-Screening",
    targetCategory: "Engineering / Technology",
  },
  {
    id: "op-laptop",
    title: "Student Developer Hardware Grant",
    provider: "Silicon Valley Hardware Alliance",
    category: "benefit",
    description: "Complimentary elite developer setup including MacBook Pro and ultra-wide monitor for promising developers without external financing.",
    requiredScore: 600,
    rewardValue: "Elite Developer Hardware Bundle",
    status: "unlocked",
    linkText: "Claim Desktop Bundle",
    targetCategory: "Engineering / Technology",
  },

  // 🏥 Medical / Healthcare
  {
    id: "op-stryker",
    title: "Stryker High-Precision Diagnostic Toolkit",
    provider: "Stryker Biotech Group",
    category: "benefit",
    description: "Complimentary premium medical kit featuring Littmann-grade stethoscopes, fiber-optic ophthalmoscopes, and student surgical dissecting instruments.",
    requiredScore: 600,
    rewardValue: "Elite Clinician Tool bundle",
    status: "unlocked",
    linkText: "Claim Medical Kit",
    targetCategory: "Medical / Healthcare",
  },
  {
    id: "op-mayo",
    title: "Mayo Clinic Clinical Rotation Fellowship",
    provider: "Mayo Foundation for Medical Education",
    category: "accelerator",
    description: "Direct fast-track clinical evaluation bypass and guaranteed interview placement into highly competitive residency and clinic research cohorts.",
    requiredScore: 740,
    rewardValue: "Priority Clinical Rotation",
    status: "locked",
    linkText: "Apply via Health-Passport",
    targetCategory: "Medical / Healthcare",
  },
  {
    id: "op-pfizer",
    title: "Pfizer Computational Biology Lab Sponsor",
    provider: "Pfizer Research Labs",
    category: "credit",
    description: "Advanced genome processing API lines and server computing node credits tailored specifically to power pharmaceutical thesis workloads.",
    requiredScore: 650,
    rewardValue: "$8,000 Sandbox Credits",
    status: "unlocked",
    linkText: "Activate Lab Sandbox",
    targetCategory: "Medical / Healthcare",
  },
  {
    id: "op-healthtech",
    title: "Healthcare Innovation & Medical Grant",
    provider: "Global Health Alliance",
    category: "scholarship",
    description: "Substantial scholastic grant providing financial and equipment assistance for student researchers tackling clinical healthcare access issues.",
    requiredScore: 700,
    rewardValue: "$12,000 Research Grant",
    status: "locked",
    linkText: "Claim Health Grant",
    targetCategory: "Medical / Healthcare",
  },

  // 💼 Commerce / Finance
  {
    id: "op-bloomberg",
    title: "Bloomberg Terminal Academic Account",
    provider: "Bloomberg LP",
    category: "benefit",
    description: "Complimentary professional educational subscription to the real-time Bloomberg Terminal analytics engine, curated for finance and cs researchers.",
    requiredScore: 640,
    rewardValue: "Free Terminal License",
    status: "unlocked",
    linkText: "Open Bloomberg Feed",
    targetCategory: "Commerce / Finance",
  },
  {
    id: "op-goldman",
    title: "Goldman Sachs Institutional Superday Fast-Track",
    provider: "Goldman Sachs & Co.",
    category: "accelerator",
    description: "Skip preliminary generic quantitative assessments and progress straight to senior executive partner rounds for major global markets summer seats.",
    requiredScore: 740,
    rewardValue: "Superday Executive Interview",
    status: "locked",
    linkText: "Request Superday Priority",
    targetCategory: "Commerce / Finance",
  },
  {
    id: "op-jpmc",
    title: "FinTech Catalyst Line of Credit",
    provider: "JPMorgan Chase Group",
    category: "financing",
    description: "Extremely low-interest student credit line designed to support proprietary model trading trials, CFA credentials enrollment, and hardware costs.",
    requiredScore: 710,
    rewardValue: "Up to $15,000 Capital Line",
    status: "locked",
    linkText: "Review Capitoline Offers",
    targetCategory: "Commerce / Finance",
  },

  // 🔬 Science / Research
  {
    id: "op-nature",
    title: "Nature Student Peer-Review Waiver",
    provider: "Nature Publishing Group",
    category: "benefit",
    description: "Comprehensive waiver of article processing charges (APC) accompanied by priority pre-print submission channels for leading open-science students.",
    requiredScore: 650,
    rewardValue: "Full APC Waiver ($3.5K Value)",
    status: "unlocked",
    linkText: "Redeem Publishing Waiver",
    targetCategory: "Science / Research",
  },
  {
    id: "op-cern",
    title: "CERN Summer Laboratory Placement Fellowship",
    provider: "CERN Scientific Alliance",
    category: "accelerator",
    description: "Guaranteed priority evaluation by project team leaders for hands-on student physics internships in Geneva, Switzerland.",
    requiredScore: 740,
    rewardValue: "Geneva Lab Fast-Track Evaluation",
    status: "locked",
    linkText: "Submit Physics Passport",
    targetCategory: "Science / Research",
  },
  {
    id: "op-nsf",
    title: "National Science Foundation Research Grant",
    provider: "National Science Foundation",
    category: "scholarship",
    description: "Merit funding block allocated directly to promote peer-verified theoretical math, statistical compute, or quantum information researcher trials.",
    requiredScore: 700,
    rewardValue: "$9,000 Science Grant stipend",
    status: "locked",
    linkText: "Forward Academic Credentials",
    targetCategory: "Science / Research",
  },

  // 🌍 Universal / Applied
  {
    id: "op-finline",
    title: "Education & Career Relocation Funding",
    provider: "Nova Apex Credit Union",
    category: "financing",
    description: "Low-interest lines of credit tailored specifically to support tuition, relocation, or hardware prototype manufacturing, requiring zero credit history.",
    requiredScore: 720,
    rewardValue: "Up to $15,000 Line",
    status: "locked",
    linkText: "Request Line Offer",
    targetCategory: "All",
  }
];

export const roadmapLevels: RoadmapLevel[] = [
  {
    level: 1,
    title: "Foundation Perks",
    minScore: 500,
    perks: ["Premium software subscriptions (JetBrains, GitHub Copilot)", "Local merchant student bundles", "Academic research access"],
    status: "unlocked",
  },
  {
    level: 2,
    title: "Technical Excellence",
    minScore: 620,
    perks: ["AWS and Azure cloud credits", "Elite mechanical developer hardware grants", "Free technical certificates sponsorship"],
    status: "active",
  },
  {
    level: 3,
    title: "Opportunity Accelerator",
    minScore: 700,
    perks: ["Tech Founders annual scholarship ($10K)", "Y-Combinator pre-screening", "Pre-qualified educational study-abroad financing"],
    status: "locked",
  },
  {
    level: 4,
    title: "Financial Autonomy",
    minScore: 740,
    perks: ["Flexible low-interest tuition loans", "Moving/relocation micro-credit for internships", "No-collateral computer hardware installment plans"],
    status: "locked",
  },
  {
    level: 5,
    title: "Institutions & Venture Elite",
    minScore: 780,
    perks: ["Pre-approved prime credit card partnerships", "$25K pre-approved seed capital lines", "Direct recruiting paths to senior engineering panels"],
    status: "locked",
  },
];

export const simulatorFactors: SimulatorFactor[] = [
  {
    id: "sim-gpa",
    label: "Supercharge Semester CGPA above 9.80",
    description: "Sustaining a perfect or near-perfect semester CGPA moves academic scores to the top-tier percentile.",
    pointsImpact: 35,
    category: "academic",
    active: false,
  },
  {
    id: "sim-kaggle",
    label: "Submit Verified LeetCode or Kaggle Stats",
    description: "Integrate competitive programming and machine learning rankings, verifying skills under rigorous standards.",
    pointsImpact: 25,
    category: "skills",
    active: false,
  },
  {
    id: "sim-internship",
    label: "Acquire & Audit Internship Offer Letter",
    description: "Uploading and auto-auditing your upcoming Software Engineer Summer internship offer adds a substantial professional component.",
    pointsImpact: 45,
    category: "professional",
    active: false,
  },
  {
    id: "sim-leadership",
    label: "Sign GDG lead or Hackathon Coordinator certificate",
    description: "Verifies high-impact collaborative work, organizing tech workshops, hackathons, or student developer teams.",
    pointsImpact: 30,
    category: "leadership",
    active: false,
  },
  {
    id: "sim-gitcycle",
    label: "Consecutive 3-Month Github Commits Streak",
    description: "Establishes long-term reliable builder credentials rather than rapid bursts of developer code.",
    pointsImpact: 20,
    category: "skills",
    active: false,
  },
];
